logging: true

salesforce:
  username: ratna-kumar.dangeti@lloydsbanking.com.devpoc
  password: Sony@4076
  consumer_key: 3MVG9od6vNol.eBijuSl01nDrsc_Ngz.DmtOGEn0Ja4DdL75sh_rzjhKqKo0C1DVygt2QyQ1xeGkrwtkfRE1L
  consumer_secret: FB008DFDC0E87E35543FBD64DB3F5EA2B7AD7789E423138986F0B4F4203C8B03
  domain: test

csv:
  filename: Tests_Orgs.csv

bigquery:
  project_ID: dmn01-rsksoi-bld-01-2017
  dataset1: your_dataset1
  
