/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	Collateral_Aggregate_BG.csv	Collateral_Aggregate_SF.csv
/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	Collateral_Type_BG.csv	Collateral_Type_SF.csv
/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	security_case_BG.csv	security_case_SF.csv
/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	account_collateral_BG.csv	account_collateral_SF.csv
/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	ccs_multi_charge_form_asset_BG.csv	ccs_multi_charge_form_asset_SF.csv
/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	Lien_BG.csv	Lien_SF.csv
/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	collateral2_BG.csv	collateral2_SF.csv
/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	ccs_deed_of_priority_BG.csv	ccs_deed_of_priority_SF.csv
/opt/homebrew/bin/python3 /Users/Ratna-Kumar.Dangeti/Documents/GitHub/csp/CSP_TestFramework/SQL/Collateral/results/compare1.py 	collateral_valuation_BG.csv	collateral_valuation_SF.csv