SELECT
ID,Name,CreatedDate,LastModifiedDate ,CCS_Amount__c,CCS_Current_Limit__c,CCS_Expiry_Date__c,CCS_Facility__c,CCS_Is_this_a_Temporary_Amendment__c,CCS_Proposed_Limit__c,CCS_Start_Date__c,CCS_Tenor__c,CCS_Utilisation__c,CreatedById,CurrencyIsoCode,LastModifiedById FROM  CCS_Limit__c
where CreatedDate >=2023-06-19T00:00:00.000Z