#dbt test --profiles-dir ./profiles --profile csp  dmn01-rsksoi-bld-01-2017.dmn01_rsksoi_euwe2_rsk_csp_downstream_raw.rskcsp_ds_account_copy
#dbt test -s source:Product_curated.Product_curated  --profiles-dir ./profiles --profile csp 
version: 2
sources:
  - name: rskcsp_ds_account_copy
    database: "dmn01-rsksoi-bld-01-2017"  
    schema: "dmn01_rsksoi_euwe2_rsk_csp_downstream_raw" 
    tables:
      - name: rskcsp_ds_account_copy
        description: Credit Suite Product 
        columns:
          - name: Id
            tests:
              - unique             
            config:
             +store_failures: true
             +schema: dmn01_rsksoi_euwe2_rsk_csp_downstream_staging                    




    